# Generated by Django 4.0 on 2021-12-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CertificatesIssued',
            fields=[
                ('serial_no', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('permissions', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
