# Generated by Django 4.0 on 2021-12-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authrequest',
            name='token',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
